In [5]:
with open("wiz_of_oz.txt", 'r', encoding='utf-8') as f:
    text = f.read()
    
print((text[:200]))

Dorothy and the Wizard in Oz


  A Faithful Record of Their Amazing Adventures
    in an Underground World; and How with the
     Aid of Their Friends Zeb Hugson, Eureka
       the Kitten, and Jim th


In [6]:
chars = sorted(set(text))
print(chars)

['\n', ' ', '!', '"', '&', "'", '(', ')', ',', '-', '.', '0', '1', '2', '3', '4', '5', '6', '7', '8', '9', ':', ';', '?', 'A', 'B', 'C', 'D', 'E', 'F', 'G', 'H', 'I', 'J', 'K', 'L', 'M', 'N', 'O', 'P', 'Q', 'R', 'S', 'T', 'U', 'V', 'W', 'Y', 'Z', 'a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j', 'k', 'l', 'm', 'n', 'o', 'p', 'q', 'r', 's', 't', 'u', 'v', 'w', 'x', 'y', 'z', '\ufeff']


In [7]:
string_to_int  = {ch:i for i,ch in enumerate(chars) }
int_ti_string = {i:ch for i, ch in enumerate(chars)}
encode = lambda s:[string_to_int[c] for c in s]
decode = lambda l:''.join([int_ti_string[i] for i in l])

In [9]:
a  = encode("Annu")

In [10]:
decode(a)

'Annu'

In [13]:
import torch

In [14]:
data = torch.tensor(encode(text), dtype = torch.long)

In [17]:
n = int(0.8*len(data))
train_data = data[:n]
val_data = data[n:]

In [22]:
block_size = 8
x = train_data[:block_size]
y = train_data[1:block_size+1]

In [23]:
for t in range(block_size):
    context = x[:t+1]
    target = y[t]
    print("when input is ",context, 'target is', target)

when input is  tensor([75]) target is tensor(27)
when input is  tensor([75, 27]) target is tensor(63)
when input is  tensor([75, 27, 63]) target is tensor(66)
when input is  tensor([75, 27, 63, 66]) target is tensor(63)
when input is  tensor([75, 27, 63, 66, 63]) target is tensor(68)
when input is  tensor([75, 27, 63, 66, 63, 68]) target is tensor(56)
when input is  tensor([75, 27, 63, 66, 63, 68, 56]) target is tensor(73)
when input is  tensor([75, 27, 63, 66, 63, 68, 56, 73]) target is tensor(1)


In [30]:
probabilites = torch.tensor([0.1,0.9])

samples = torch.multinomial(probabilites, num_samples=10,replacement=True)
print(samples)

tensor([1, 1, 1, 1, 1, 1, 1, 1, 1, 0])


In [33]:
tensor = torch.tensor([1,2,3,4])
out = torch.cat((tensor, torch.tensor([5])), dim=0)
out

tensor([1, 2, 3, 4, 5])

In [35]:
out = torch.tril(torch.ones(5,5)) # triangle lower
out

tensor([[1., 0., 0., 0., 0.],
        [1., 1., 0., 0., 0.],
        [1., 1., 1., 0., 0.],
        [1., 1., 1., 1., 0.],
        [1., 1., 1., 1., 1.]])

In [36]:
out = torch.triu(torch.ones(5,5)) # triangle upper
out

tensor([[1., 1., 1., 1., 1.],
        [0., 1., 1., 1., 1.],
        [0., 0., 1., 1., 1.],
        [0., 0., 0., 1., 1.],
        [0., 0., 0., 0., 1.]])

In [39]:
out = torch.zeros(5,5).masked_fill(torch.tril(torch.ones(5,5))==0, float('-inf'))
out

tensor([[0., -inf, -inf, -inf, -inf],
        [0., 0., -inf, -inf, -inf],
        [0., 0., 0., -inf, -inf],
        [0., 0., 0., 0., -inf],
        [0., 0., 0., 0., 0.]])

In [40]:
torch.exp(out)

tensor([[1., 0., 0., 0., 0.],
        [1., 1., 0., 0., 0.],
        [1., 1., 1., 0., 0.],
        [1., 1., 1., 1., 0.],
        [1., 1., 1., 1., 1.]])

In [41]:
input = torch.zeros(2,3,4)
out = input.transpose(0,2)
out.shape

torch.Size([4, 3, 2])

In [42]:
t1 = torch.tensor([1,2,3])
t2 = torch.tensor([4,5,6])
t3 = torch.tensor([7,8,9])

stacked_tensor = torch.stack([t1,t2,t2])
stacked_tensor

tensor([[1, 2, 3],
        [4, 5, 6],
        [4, 5, 6]])

In [44]:
import torch.nn as nn
sample = torch.tensor([10.0,10.0,10.0])
linear = nn.Linear(3,3,bias=False)
print(linear(sample))

tensor([ 4.8822,  6.8594, -1.6966], grad_fn=<SqueezeBackward4>)


In [47]:
import torch.nn.functional as F

t1 = torch.tensor([1.0,2.0,3.0])
softmax_out = F.softmax(t1, dim=0)
softmax_out

tensor([0.0900, 0.2447, 0.6652])

In [49]:
import torch.nn as nn
sample = torch.tensor([10.0,10.0,10.0])
linear = nn.Linear(3,10,bias=False)
print(linear(sample))

tensor([ 5.0288, 10.6309, -0.8169,  0.2804, -0.5542, -6.3958, -8.8486, -1.9494,
        -5.2861, -4.9472], grad_fn=<SqueezeBackward4>)


In [53]:
vocab_size = 1000
embedding_dim = 100
embedding = nn.Embedding(vocab_size ,embedding_dim)

input_indices = torch.LongTensor([1,4,2,7])
emb_out = embedding(input_indices)
emb_out.shape

torch.Size([4, 100])

In [56]:
a = torch.tensor([[2,3],[5,4]])
b = torch.tensor([[2,3],[5,4]])

In [67]:
a = torch.tensor([[1,2],[3,4],[5,6]])
b = torch.tensor([[7,8,9],[10,11,12]])

In [70]:
a@b # @ = mat multiplication equivalent to torch.matmul

tensor([[ 27,  30,  33],
        [ 61,  68,  75],
        [ 95, 106, 117]])

In [84]:
int_64 = torch.randint(4,30,(3,3)) # low, high, shape
int_64

tensor([[18, 13, 15],
        [28, 29, 23],
        [18, 28, 11]])

In [86]:
float_32 = torch.rand(3,6)
float_32

tensor([[0.5381, 0.8334, 0.3620, 0.7139, 0.4220, 0.1095],
        [0.9496, 0.0718, 0.7455, 0.3024, 0.8090, 0.6000],
        [0.1969, 0.3433, 0.5676, 0.1066, 0.3918, 0.6449]])

In [87]:
torch.matmul(int_64.float(),float_32) # dtype should be same for matmul
# int_64.float() will cast int into float

tensor([[24.9837, 21.0845, 24.7213, 18.3817, 23.9892, 19.4438],
        [47.1334, 33.3142, 44.8099, 31.2127, 44.2867, 35.2973],
        [38.4402, 20.7889, 33.6332, 22.4913, 34.5565, 25.8637]])

In [103]:
device = 'cuda' if torch.cuda.is_available() else 'cpu'
n = int(0.8*(len(data)))
train_data = data[:n]
val_data = data[n:]
batch_size = 8
def get_batch(split):
    data = train_data if split == 'train' else val_data
    ix = torch.randint(len(data)-block_size, (batch_size,))
    print(ix)
    
    x = torch.stack([data[i:i+batch_size] for i in ix])
    y = torch.stack([data[i:i+batch_size+1] for i in ix])
    
    x,y = x.to(device), y.to(device)
    return x,y

In [104]:
x,y = get_batch(train_data)

tensor([ 3513, 35788,  8292, 40672, 28342, 16704, 41431, 32359])


In [105]:
from torch.nn import functional as F

In [ ]:
class BigramLM(nn.Module):
    def __init__(self, vocal_size):
        super().__init__()
        self.token_embedding_table = nn.Embedding(vocab_size, vocab_size)
        
    def forward(self,index, targets):
        logits = self.token_embedding_table(index)
        return logits